### ISSUE TITLE
Plano para atualização do TW

### ISSUE THREAD

**Issue by andrefelipefraga** [eloverde-sistemas/ng-tailwind#1]
- Migrar Anexo para NGT;
- Ajustes para deixar NGT genérico;
- Ajustes do componete de anexo para dar zoom in e out, girar, navegar para frente e para trás;
- TextEditor
- Documentação;

**Comment by wilianx7** [comment]
* Migrar Anexo para NGT (Concluído);
* Ajustes para deixar NGT genérico (Concluído);

* Ajustes do componete de anexo para dar zoom in e out, girar, navegar para frente e para trás (Issue #2);
* TextEditor (Issue #3);
* Documentação (Issue #4).
