### ISSUE TITLE
Tooltip nas colunas que possuem habilitado ordenação

### ISSUE THREAD

**Issue by andrefelipefraga** [eloverde-sistemas/ng-tailwind#11]
Apresentar tooltip nas colunas que possuem  ordenação habilitada, onde:
- Sem ordenação: "Ordenar de A a Z" (seta para baixo)
- Quando estiver ordenado ascendentemente: "Ordenar de Z a A"
- Quando estiver ordenado decrescentemente: "Limpar ordenação"

**Comment by wilianx7** [comment]
Olá @andrefelipefraga, foram adicionadas as seguintes modificações para satisfazer a sua necessidade:

* Adicionado @Input() sortableTooltip para o componente NgtThComponent;
* Adicionada interface NgtSortableTooltip para o componente NgtThComponent;
* O valor passado para o @Input() sortableTooltip deve seguir a interface NgtSortableTooltip;

### Interface
![image](https://user-images.githubusercontent.com/42422976/77644074-3d486980-6f3f-11ea-87a4-4db1dd6a0388.png)

### Exemplo de uso
![image](https://user-images.githubusercontent.com/42422976/77644115-50f3d000-6f3f-11ea-94fa-da76db16dad4.png)

![image](https://user-images.githubusercontent.com/42422976/77644224-754fac80-6f3f-11ea-96f0-1a44359132f8.png)
