### ISSUE TITLE
[NGT Datatable] Após selecionar tudo e excluir lista inteira, a opção de selecionar tudo fica selecionado

### ISSUE THREAD

**Issue by filipedtristao** [eloverde-sistemas/ng-tailwind#12]
Após selecionar tudo e fazer algum filtro, excluir registros ou tomar uma ação que mude o conteúdo carregado da datatable, o checkbox de "selecionar todos" continua marcado.

![image](https://user-images.githubusercontent.com/10791793/77564348-58649c00-6ea1-11ea-981e-0ee198a5ef00.png)

**Comment by wilianx7** [comment]
Essa situação estava ocorrendo devido ao fato de que quando a NgtDatatable executava o método ```Apply()```, os elementos selecionados da tabela (```selectedElements```) eram resetados. No entanto, como a checkbox relacionada ao componente ```NgtThCheck``` não faz parte dessa listagem de elementos selecionados em nenhum momento, ela permanecia com o seu último valor.

Para corrigir essa problema, adicionei no componente ```NgtThCheck``` um subscribe no evento ```onDataChange``` com o objetivo de setar o valor dessa checkbox como ```false``` sempre que houver uma atualização nos dados da tabela.

![image](https://user-images.githubusercontent.com/42422976/77651637-d8dfd700-6f4b-11ea-9fe1-e6c75899fa69.png)
