### ISSUE TITLE
Preview para anexos

### ISSUE THREAD

**Issue by wilianx7** [eloverde-sistemas/ng-tailwind#2]
- Estudar o que é necessário para realizar esta issue antes de implementar. 
- Avaliar possibilidade de preview por tipo de documento, por exemplo, é mais fácil fazer primeiro somente imagens do que PDF.
- Tipos de documentos passível preview: imagens, PDF, audios.
- Verificar se é possível otimizar o carregamento das imagens para o front (caso do bola que abre todas as imagens das tarefas).

* Pesquisar componente que permita realizar um preview a partir de um ou vários anexos, sendo possível realizar as ações: 
* Zoom In;
* Zoom Out; 
* Girar; 
* Navegar para frente e para trás.

* Adaptar esse componente para o Ng Tailwind e torná-lo genérico.

**Comment by andrefelipefraga** [comment]
Permitir visualizar PDF e audios no componente.

**Comment by wilianx7** [comment]
A maioria, se não todos, os requisitos já foram atendidos pelo componente desenvolvido pelo @NicollasMatheus37 e acoplado ao NgtDropdown.
