### ISSUE TITLE
Stripped lines nas tabelas do tailwind

### ISSUE THREAD

**Issue by andrefelipefraga** [eloverde-sistemas/ng-tailwind#20]
Deixar as tabelas em TW uma linha em branco e outra cinza, tal como é na tabela abaixo:

![image](https://user-images.githubusercontent.com/26805252/78362429-78c2e380-7590-11ea-99c0-314db9a0c27a.png)

**Comment by filipedtristao** [comment]
Colocar @Input na TR do ng-tailwind que aplique classes dessa forma:

![image](https://user-images.githubusercontent.com/10791793/78362567-b889cb00-7590-11ea-87e1-cc6b6e1e22da.png)

Talvez as cores aplicadas para par e ímpar podem ser definidas via ngt-style, verificar melhor forma de fazer.
