### ISSUE TITLE
Melhorias no ngt-select

### ISSUE THREAD

**Issue by eloverde-sistemas** [eloverde-sistemas/ng-tailwind#35]
Atualmente não é possível excluir individualmente um registro do componente, somente todos e term que adicionar tudo novamente.
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/41301622/88832199-d82fa980-d1a6-11ea-8fc8-0e5d23c8f9cd.png">

Melhoria desenhada: que haja um x ao lado de cada registro e que o usuário possa excluir individualmente ou todos como é hoje. Por exemplo:

<img width="429" alt="image" src="https://user-images.githubusercontent.com/41301622/88832333-0ad9a200-d1a7-11ea-9cf0-527a485b3a0e.png">

**Comment by andrefelipefraga** [comment]
O Adicionar deveria ser a primeira opção, hoje tem que escrolar para baixo para encontrar e selecionar.

<img width="1301" alt="Screen Shot 2020-08-31 at 02 02 42" src="https://user-images.githubusercontent.com/26805252/91684614-5ed10100-eb2e-11ea-8ed2-33d42bb99a64.png">

**Comment by wilianx7** [comment]
Para excluir os itens individualmente, basta selecionar o mesmo item novamente e ele será removido. Esse comportamento, é controlado internamente pelo ng-select, que é o componente utilizado no wrapper do NgtSelect. Portanto, não é possível mudar.

Com relação a opção de "adicionar", já foram abertas issues com relação a isso no ng-select e os desenvolvedores parecem não concordar que essa opção deveria estar no topo: 

https://github.com/ng-select/ng-select/issues/377

**Comment by wilianx7** [comment]
Opção para excluir itens individualmente adicionada na versão 0.0.173 conforme solicitado.
