### ISSUE TITLE
Problema com popups quando tem apenas 1 registro na ng-datatable

### ISSUE THREAD

**Issue by eloverde-sistemas** [eloverde-sistemas/ng-tailwind#37]
![telegram-cloud-photo-size-1-4992484132948912238-y](https://user-images.githubusercontent.com/41301622/89292766-42c36800-d633-11ea-97f5-15a0a4122991.jpg)

**Comment by wilianx7** [comment]
Esse problema está acontecendo porque a NgtDatatable possui um overflow-x-auto que quando presente é interpretado pelos navegadores como overflow-y-auto também mesmo que a classe overflow-y-visible esteja presente na NgtDatatable.

![image](https://user-images.githubusercontent.com/42422976/90776003-ecf7ec80-e2cf-11ea-864a-cfcc497f47f4.png)

Desse modo, caso o overflow-x-auto seja removido, o problema deixará de acontecer para alguns casos como, por exemplo, o citado acima. No entanto, nos casos em que a NgtDatable estiver dentro de outro componente que possua um overflow-auto, o problema voltará a acontecer. Além disso, ao remover o overflow-x-auto da NgtDatatable, cria-se outro problema tendo em vista que em certas aplicações essa scroll no eixo do X pode ser necessária.

**Comment by wilianx7** [comment]
Resolvido com a inversão automática de orientação do NgtDropdown.
