### ISSUE TITLE
NGT-Input não está permitindo limpar 

### ISSUE THREAD

**Issue by eloverde-sistemas** [eloverde-sistemas/ng-tailwind#42]
Eu clico no x do campo e o campo não é limpo:

<img width="417" alt="Screen Shot 2020-09-12 at 16 59 02" src="https://user-images.githubusercontent.com/41301622/93003958-61156100-f519-11ea-92c2-c8043e3a06fa.png">

Se eu tento apagar os caracteres, ao apagar o ultimo, o componente automaticamente volta todo o texto digitado.

Fonte:

<img width="936" alt="image" src="https://user-images.githubusercontent.com/41301622/93003967-74283100-f519-11ea-9865-aba9b7173b59.png">

**Comment by wilianx7** [comment]
Não consegui reproduzir. A princípio está correto.
